child_meal = int(input(" What is the price of a child's meal? "))
adult_meal = int(input("What is the price of an adult's name? "))
num_child = int(input("How many children are there? "))
num_adult = int(input("How many adults are there? "))
tax_rate = int(input("What is the sales tax rate? "))
total = ((adult_meal * num_adults)+(child_meal * num_child))
print("")
print("Subtotal: ")
print("Sales Tax: ")
print("Total: ")
print("")
pay_amount = input("What is the payment amount? ")
change = pay_amount - total
print("Change: ")