print(" ")
print("Please enter the following information:")
print(" ")
firstN = input("First name: ")
lastN = input("Last name: ")
email = input("Email address: ")
phoneN = input("Phone number: ")
jobT = input("Job title: ")
idN = input("ID number: ")
hairC = input("Hair color: ")
eyeC = input("Eye color: ")
month = input("Current month: ")
training = input("Are you training: ")
print(" ")

print("The ID Card is:")
print("=========================================")
print(lastN + ", " + firstN)
print(jobT)
print("ID: " + idN)
print(" ")
print(email)
print(phoneN)
print(" ")
print("Hair: " + hairC + "\t\tEyes: " + eyeC)
print("Month: " + month + "\t\tTraining: " + training)
print("=========================================")